apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nimakaviani/idpbuilder
    targetRevision: common-ref
    path: "examples/ref-implementation/argo-workflows/manifests/dev"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
