apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/nimakaviani/idpbuilder
    targetRevision: common-ref
    path: "examples/ref-implementation/coredns/manifests"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
