apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    example: ref-implementation
spec:
  destination:
    namespace: keycloak
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://github.com/nimakaviani/idpbuilder
    targetRevision: common-ref
    path: "examples/ref-implementation/keycloak/manifests"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
